name: Build VSCode Extension

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Install VSCE
        run: npm install -g @vscode/vsce

      - name: Package VSCode Extension
        run: vsce package --out encodex.vsix

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: encodex
          path: encodex.vsix
          retention-days: 1
