name: Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0
      upload-to-marketplace:
        description: Upload to marketplace
        required: true
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: encodex
          path: .

      - name: Rename Build Artifact
        run: mv ./encodex.vsix encodex-${{ github.event.inputs.build-ver }}.vsix

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.build-ver }}
          name: Release ${{ github.event.inputs.build-ver }}
          files: |
            ./encodex-${{ github.event.inputs.build-ver }}.vsix
          draft: false
          prerelease: false
          make_latest: true
          body_path: ./CHANGELOG.md
